version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: heart_disease_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: heart_disease_db
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - heart_disease_network

  # FastAPI Backend
  backend:
    build: .
    container_name: heart_disease_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: mongodb://admin:password123@mongodb:27017/heart_disease_db?authSource=admin
      DATABASE_NAME: heart_disease_db
      SECRET_KEY: your-super-secret-key-change-in-production
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    volumes:
      - ./uploads:/app/uploads
      - ./heart_disease_data.csv:/app/heart_disease_data.csv
    depends_on:
      - mongodb
    networks:
      - heart_disease_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/dashboard/stats"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: heart_disease_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    networks:
      - heart_disease_network

volumes:
  mongodb_data:
    driver: local

networks:
  heart_disease_network:
    driver: bridge